-- AlterEnum NotificationType: add admin notification values
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_DEADLINE_REMINDER_7D';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_DEADLINE_REMINDER_2D';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_DEADLINE_TODAY';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_COURSE_STARTING';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_ALL_REGISTRIES_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_CV_DPR445_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_MATERIAL_PENDING';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_ACCOUNT_LOCKED';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_ATTENDANCE_BELOW_MIN';
ALTER TYPE "NotificationType" ADD VALUE 'ADMIN_DAILY_SUMMARY';
